package com.nzl.dao;

import com.nzl.dao.provider.ParentBlogTypeSqlProvider;
import com.nzl.pojo.ParentBlogType;
import org.apache.ibatis.annotations.*;
import org.apache.ibatis.type.JdbcType;

public interface ParentBlogTypeMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table parent_blog_type
     *
     * @mbg.generated
     */
    @Delete({
        "delete from parent_blog_type",
        "where parent_blog_type_id = #{parentBlogTypeId,jdbcType=TINYINT}"
    })
    int deleteByPrimaryKey(Byte parentBlogTypeId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table parent_blog_type
     *
     * @mbg.generated
     */
    @Insert({
        "insert into parent_blog_type (parent_blog_type_id, name, ",
        "gmt_modified, gmt_create)",
        "values (#{parentBlogTypeId,jdbcType=TINYINT}, #{name,jdbcType=CHAR}, ",
        "#{gmtModified,jdbcType=TIMESTAMP}, #{gmtCreate,jdbcType=TIMESTAMP})"
    })
    int insert(ParentBlogType record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table parent_blog_type
     *
     * @mbg.generated
     */
    @InsertProvider(type= ParentBlogTypeSqlProvider.class, method="insertSelective")
    int insertSelective(ParentBlogType record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table parent_blog_type
     *
     * @mbg.generated
     */
    @Select({
        "select",
        "parent_blog_type_id, name, gmt_modified, gmt_create",
        "from parent_blog_type",
        "where parent_blog_type_id = #{parentBlogTypeId,jdbcType=TINYINT}"
    })
    @Results({
        @Result(column="parent_blog_type_id", property="parentBlogTypeId", jdbcType=JdbcType.TINYINT, id=true),
        @Result(column="name", property="name", jdbcType=JdbcType.CHAR),
        @Result(column="gmt_modified", property="gmtModified", jdbcType=JdbcType.TIMESTAMP),
        @Result(column="gmt_create", property="gmtCreate", jdbcType=JdbcType.TIMESTAMP)
    })
    ParentBlogType selectByPrimaryKey(Byte parentBlogTypeId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table parent_blog_type
     *
     * @mbg.generated
     */
    @UpdateProvider(type=ParentBlogTypeSqlProvider.class, method="updateByPrimaryKeySelective")
    int updateByPrimaryKeySelective(ParentBlogType record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table parent_blog_type
     *
     * @mbg.generated
     */
    @Update({
        "update parent_blog_type",
        "set name = #{name,jdbcType=CHAR},",
          "gmt_modified = #{gmtModified,jdbcType=TIMESTAMP},",
          "gmt_create = #{gmtCreate,jdbcType=TIMESTAMP}",
        "where parent_blog_type_id = #{parentBlogTypeId,jdbcType=TINYINT}"
    })
    int updateByPrimaryKey(ParentBlogType record);
}