server:
  port: 8082

spring:
  profiles:
    include: email,mysql,redis

  servlet:
    multipart:
      maxFileSize: 100MB
      maxRequestSize: 100MB

  mvc:
    static-path-pattern: /**
    throw-exception-if-no-handler-found: true


mybatis:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  mapper-locations: classpath*:mapper/*.xml


logging:
  level:
    com.neo.mapper: DEBUG

pagehelper:
  helperDialect: mysql
  reasonable: true
  supportMethodsArguments: true
  params: count=countSql
