server:
  port: 8080

spring:
  profiles:
    include: mysql,redis,email

  servlet:
    multipart:
      maxFileSize: 100MB
      maxRequestSize: 100MB

  mvc:
    static-path-pattern: /**


mybatis:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl


logging:
  level:
    com.neo.mapper: DEBUG

# 上传路径
## 头像上传路径
upload:
  path:
    portrait: G:/IDEA/ZeusBlog/zeus-server/src/main/resources/static/upload/portrait
    ## 博客上传路径
    blog: G:/data
