server:
  port: 8082

spring:
  profiles:
    include: email,mysql,redis

  servlet:
    multipart:
      maxFileSize: 100MB
      maxRequestSize: 100MB

  mvc:
    static-path-pattern: /**
    throw-exception-if-no-handler-found: true

  resources:
    static-locations: classpath:/static/,file:/Users/zonst/workspace/upload-img/


mybatis:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  mapper-locations: classpath*:mapper/*.xml


logging:
  level:
    com.neo.mapper: DEBUG

pagehelper:
  reasonable: true
  params: count=countSql
  helper-dialect: mysql
  support-methods-arguments: true
