package com.nzl.dao.provider;

import com.nzl.pojo.BlogType;
import org.apache.ibatis.jdbc.SQL;

public class BlogTypeSqlProvider {

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table blog_type
     *
     * @mbg.generated
     */
    public String insertSelective(BlogType record) {
        SQL sql = new SQL();
        sql.INSERT_INTO("blog_type");
        
        if (record.getBlogTypeId() != null) {
            sql.VALUES("blog_type_id", "#{blogTypeId,jdbcType=TINYINT}");
        }
        
        if (record.getParentBlogTypeId() != null) {
            sql.VALUES("parent_blog_type_id", "#{parentBlogTypeId,jdbcType=TINYINT}");
        }
        
        if (record.getBlogTypeName() != null) {
            sql.VALUES("blog_type_name", "#{blogTypeName,jdbcType=CHAR}");
        }
        
        if (record.getGmtModified() != null) {
            sql.VALUES("gmt_modified", "#{gmtModified,jdbcType=TIMESTAMP}");
        }
        
        if (record.getGmtCreate() != null) {
            sql.VALUES("gmt_create", "#{gmtCreate,jdbcType=TIMESTAMP}");
        }
        
        return sql.toString();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table blog_type
     *
     * @mbg.generated
     */
    public String updateByPrimaryKeySelective(BlogType record) {
        SQL sql = new SQL();
        sql.UPDATE("blog_type");
        
        if (record.getParentBlogTypeId() != null) {
            sql.SET("parent_blog_type_id = #{parentBlogTypeId,jdbcType=TINYINT}");
        }
        
        if (record.getBlogTypeName() != null) {
            sql.SET("blog_type_name = #{blogTypeName,jdbcType=CHAR}");
        }
        
        if (record.getGmtModified() != null) {
            sql.SET("gmt_modified = #{gmtModified,jdbcType=TIMESTAMP}");
        }
        
        if (record.getGmtCreate() != null) {
            sql.SET("gmt_create = #{gmtCreate,jdbcType=TIMESTAMP}");
        }
        
        sql.WHERE("blog_type_id = #{blogTypeId,jdbcType=TINYINT}");
        
        return sql.toString();
    }
}