package com.nzl.dao.provider;

import com.nzl.pojo.ParentBlogType;
import org.apache.ibatis.jdbc.SQL;

public class ParentBlogTypeSqlProvider {

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table parent_blog_type
     *
     * @mbg.generated
     */
    public String insertSelective(ParentBlogType record) {
        SQL sql = new SQL();
        sql.INSERT_INTO("parent_blog_type");
        
        if (record.getParentBlogTypeId() != null) {
            sql.VALUES("parent_blog_type_id", "#{parentBlogTypeId,jdbcType=TINYINT}");
        }
        
        if (record.getName() != null) {
            sql.VALUES("name", "#{name,jdbcType=CHAR}");
        }
        
        if (record.getGmtModified() != null) {
            sql.VALUES("gmt_modified", "#{gmtModified,jdbcType=TIMESTAMP}");
        }
        
        if (record.getGmtCreate() != null) {
            sql.VALUES("gmt_create", "#{gmtCreate,jdbcType=TIMESTAMP}");
        }
        
        return sql.toString();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table parent_blog_type
     *
     * @mbg.generated
     */
    public String updateByPrimaryKeySelective(ParentBlogType record) {
        SQL sql = new SQL();
        sql.UPDATE("parent_blog_type");
        
        if (record.getName() != null) {
            sql.SET("name = #{name,jdbcType=CHAR}");
        }
        
        if (record.getGmtModified() != null) {
            sql.SET("gmt_modified = #{gmtModified,jdbcType=TIMESTAMP}");
        }
        
        if (record.getGmtCreate() != null) {
            sql.SET("gmt_create = #{gmtCreate,jdbcType=TIMESTAMP}");
        }
        
        sql.WHERE("parent_blog_type_id = #{parentBlogTypeId,jdbcType=TINYINT}");
        
        return sql.toString();
    }
}