package com.nzl.dao.provider;

import com.nzl.pojo.Sign;
import org.apache.ibatis.jdbc.SQL;

public class SignSqlProvider {

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sign
     *
     * @mbg.generated
     */
    public String insertSelective(Sign record) {
        SQL sql = new SQL();
        sql.INSERT_INTO("sign");
        
        if (record.getSignId() != null) {
            sql.VALUES("sign_id", "#{signId,jdbcType=BIGINT}");
        }
        
        if (record.getUid() != null) {
            sql.VALUES("uid", "#{uid,jdbcType=VARCHAR}");
        }
        
        if (record.getStatus() != null) {
            sql.VALUES("status", "#{status,jdbcType=CHAR}");
        }
        
        if (record.getMonthDay() != null) {
            sql.VALUES("month_day", "#{monthDay,jdbcType=TINYINT}");
        }
        
        if (record.getTotalDay() != null) {
            sql.VALUES("total_day", "#{totalDay,jdbcType=INTEGER}");
        }
        
        if (record.getTime() != null) {
            sql.VALUES("time", "#{time,jdbcType=TIMESTAMP}");
        }
        
        if (record.getGmtModified() != null) {
            sql.VALUES("gmt_modified", "#{gmtModified,jdbcType=TIMESTAMP}");
        }
        
        if (record.getGmtCreate() != null) {
            sql.VALUES("gmt_create", "#{gmtCreate,jdbcType=TIMESTAMP}");
        }
        
        return sql.toString();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sign
     *
     * @mbg.generated
     */
    public String updateByPrimaryKeySelective(Sign record) {
        SQL sql = new SQL();
        sql.UPDATE("sign");
        
        if (record.getUid() != null) {
            sql.SET("uid = #{uid,jdbcType=VARCHAR}");
        }
        
        if (record.getStatus() != null) {
            sql.SET("status = #{status,jdbcType=CHAR}");
        }
        
        if (record.getMonthDay() != null) {
            sql.SET("month_day = #{monthDay,jdbcType=TINYINT}");
        }
        
        if (record.getTotalDay() != null) {
            sql.SET("total_day = #{totalDay,jdbcType=INTEGER}");
        }
        
        if (record.getTime() != null) {
            sql.SET("time = #{time,jdbcType=TIMESTAMP}");
        }
        
        if (record.getGmtModified() != null) {
            sql.SET("gmt_modified = #{gmtModified,jdbcType=TIMESTAMP}");
        }
        
        if (record.getGmtCreate() != null) {
            sql.SET("gmt_create = #{gmtCreate,jdbcType=TIMESTAMP}");
        }
        
        sql.WHERE("sign_id = #{signId,jdbcType=BIGINT}");
        
        return sql.toString();
    }
}