package com.nzl.dao.provider;

import com.nzl.pojo.UserType;
import org.apache.ibatis.jdbc.SQL;

public class UserTypeSqlProvider {

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_type
     *
     * @mbg.generated
     */
    public String insertSelective(UserType record) {
        SQL sql = new SQL();
        sql.INSERT_INTO("user_type");
        
        if (record.getUserTypeId() != null) {
            sql.VALUES("user_type_id", "#{userTypeId,jdbcType=INTEGER}");
        }
        
        if (record.getUid() != null) {
            sql.VALUES("uid", "#{uid,jdbcType=VARCHAR}");
        }
        
        if (record.getName() != null) {
            sql.VALUES("name", "#{name,jdbcType=CHAR}");
        }
        
        if (record.getGmtCreate() != null) {
            sql.VALUES("gmt_create", "#{gmtCreate,jdbcType=TIMESTAMP}");
        }
        
        if (record.getGmtModified() != null) {
            sql.VALUES("gmt_modified", "#{gmtModified,jdbcType=TIMESTAMP}");
        }
        
        return sql.toString();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_type
     *
     * @mbg.generated
     */
    public String updateByPrimaryKeySelective(UserType record) {
        SQL sql = new SQL();
        sql.UPDATE("user_type");
        
        if (record.getUid() != null) {
            sql.SET("uid = #{uid,jdbcType=VARCHAR}");
        }

        if (record.getName() != null) {
            sql.SET("name = #{name,jdbcType=CHAR}");
        }

        if (record.getGmtCreate() != null) {
            sql.SET("gmt_create = #{gmtCreate,jdbcType=TIMESTAMP}");
        }

        if (record.getGmtModified() != null) {
            sql.SET("gmt_modified = #{gmtModified,jdbcType=TIMESTAMP}");
        }

        sql.WHERE("user_type_id = #{userTypeId,jdbcType=INTEGER}");
        
        return sql.toString();
    }
}