package com.nzl.dao.provider;

import com.nzl.pojo.User;
import org.apache.ibatis.jdbc.SQL;

public class UserSqlProvider {

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user
     *
     * @mbg.generated
     */
    public String insertSelective(User record) {
        SQL sql = new SQL();
        sql.INSERT_INTO("user");

        if (record.getUid() != null) {
            sql.VALUES("uid", "#{uid,jdbcType=VARCHAR}");
        }

        if (record.getUsername() != null) {
            sql.VALUES("username", "#{username,jdbcType=CHAR}");
        }

        if (record.getPassword() != null) {
            sql.VALUES("password", "#{password,jdbcType=CHAR}");
        }

        if (record.getRealName() != null) {
            sql.VALUES("real_name", "#{realName,jdbcType=CHAR}");
        }

        if (record.getGender() != null) {
            sql.VALUES("gender", "#{gender,jdbcType=CHAR}");
        }

        if (record.getBirthday() != null) {
            sql.VALUES("birthday", "#{birthday,jdbcType=DATE}");
        }

        if (record.getHeadPortraitUrl() != null) {
            sql.VALUES("head_portrait_url", "#{headPortraitUrl,jdbcType=VARCHAR}");
        }

        if (record.getIntroduction() != null) {
            sql.VALUES("introduction", "#{introduction,jdbcType=VARCHAR}");
        }

        if (record.getJoinTime() != null) {
            sql.VALUES("join_time", "#{joinTime,jdbcType=DATE}");
        }

        if (record.getEmail() != null) {
            sql.VALUES("email", "#{email,jdbcType=VARCHAR}");
        }

        if (record.getPhone() != null) {
            sql.VALUES("phone", "#{phone,jdbcType=CHAR}");
        }

        if (record.getSalt() != null) {
            sql.VALUES("salt", "#{salt,jdbcType=VARCHAR}");
        }

        if (record.getStatus() != null) {
            sql.VALUES("status", "#{status,jdbcType=CHAR}");
        }

        if (record.getGmtCreate() != null) {
            sql.VALUES("gmt_create", "#{gmtCreate,jdbcType=TIMESTAMP}");
        }

        if (record.getGmtModified() != null) {
            sql.VALUES("gmt_modified", "#{gmtModified,jdbcType=TIMESTAMP}");
        }

        return sql.toString();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user
     *
     * @mbg.generated
     */
    public String updateByPrimaryKeySelective(User record) {
        SQL sql = new SQL();
        sql.UPDATE("user");

        if (record.getUsername() != null) {
            sql.SET("username = #{username,jdbcType=CHAR}");
        }

        if (record.getPassword() != null) {
            sql.SET("password = #{password,jdbcType=CHAR}");
        }

        if (record.getRealName() != null) {
            sql.SET("real_name = #{realName,jdbcType=CHAR}");
        }

        if (record.getGender() != null) {
            sql.SET("gender = #{gender,jdbcType=CHAR}");
        }

        if (record.getBirthday() != null) {
            sql.SET("birthday = #{birthday,jdbcType=DATE}");
        }

        if (record.getHeadPortraitUrl() != null) {
            sql.SET("head_portrait_url = #{headPortraitUrl,jdbcType=VARCHAR}");
        }

        if (record.getIntroduction() != null) {
            sql.SET("introduction = #{introduction,jdbcType=VARCHAR}");
        }

        if (record.getJoinTime() != null) {
            sql.SET("join_time = #{joinTime,jdbcType=DATE}");
        }

        if (record.getEmail() != null) {
            sql.SET("email = #{email,jdbcType=VARCHAR}");
        }

        if (record.getPhone() != null) {
            sql.SET("phone = #{phone,jdbcType=CHAR}");
        }

        if (record.getStatus() != null) {
            sql.SET("status = #{status,jdbcType=CHAR}");
        }

        if (record.getGmtCreate() != null) {
            sql.SET("gmt_create = #{gmtCreate,jdbcType=TIMESTAMP}");
        }

        if (record.getGmtModified() != null) {
            sql.SET("gmt_modified = #{gmtModified,jdbcType=TIMESTAMP}");
        }

        sql.WHERE("uid = #{uid,jdbcType=VARCHAR}");

        return sql.toString();
    }


    /**
     * 动态查询参数
     *
     * @param param String
     * @return
     */
    public String dynamicQuery(String param, String value) {
        String sql = "select count(" + param + ") from user where "
                + param + "='" + value + "'";

        return sql;
    }
}